version: '3.4'
services:

  #PHP Service
  app:
    image: anhanh:v1
    user: root
    volumes:
      - ./:/var/www/html

  #Nginx Service
  webserver:
    image: nginx:1.17-alpine
    ports:
      - "9000:80"
    volumes:
      - ./:/var/www/html
      - ./nginx.conf:/etc/nginx/conf.d/default.conf
  db:
    image: "mariadb:10.1.30"
    environment:
      MYSQL_ROOT_PASSWORD: "1"
      MYSQL_DATABASE: "anhanh"
    ports:
      - "33062:3306"
    volumes:
      - ./mysql:/var/lib/mysql
